### PR TITLE
immediately fire a timer set to a negative duration

### LINKED ISSUE #49: timer set to a negative duration doesn't fire until clock is advanced
I would have expected the following timer to fire immediately:
```go
clock := NewMock()
timer := clock.Timer(-time.Second)
```

It doesn't fire until the clock is advanced though.

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #49.

### CODE REVIEW

**Comment by marten-seemann** [comment]
@benbjohnson Friendly ping, would you mind reviewing this PR?

**Review by djmitche — COMMENTED** [review]
How does this compare to the behavior of the `time` package?

**Comment by marten-seemann** [comment]
It's equivalent to what the `time` package does.

**Review by Mohamed01mmm — APPROVED** [review]

**Comment by djmitche** [comment]
Thanks!

**Comment by benbjohnson** [comment]
@marten-seemann Sorry for my slow response. Go ahead and merge as you see fit. :+1

**Comment by marten-seemann** [comment]
@benbjohnson I don't think I have merge permissions in this repo.

**Comment by djmitche** [comment]
I already merged it :)

**Comment by marten-seemann** [comment]
@benbjohnson Could we ask for a new release including this fix at some point please? 🙏

**Comment by benbjohnson** [comment]
No problem: https://github.com/benbjohnson/clock/releases/tag/v1.3.4

**Pull request merged**
