### PR TITLE
Add WithDeadline/WithTimeout context functions

### PR DESCRIPTION
**Pull request by morigs**
This is renewal of #20 
It's rebased on latest changes from master now.
I've also added usage of `Until` instead of `Sub` as well as some basic tests

### CODE REVIEW

**Review by djmitche — APPROVED** [review]
This looks good!  Thanks!

What do you think about also adding `clock.WithCancel`?  Using this will require calling `clock.WithFoo` instead of `context.WithFoo`, and it might be easier for users to remember to change all uses of `context.WithFoo` rather than just two of the three.  WDYT?

**Comment by morigs** [comment]
Tbh I think it's better to provide a facade for the whole package. But historically, clock hide only some types and functions from time. Probably the same logic should apply for context.
But on the other hand, your point on usage consistency is also valid. So I don't have a strong opinion.
The only thing I can say - adding `WithCancel` will require some rework because initial implementation of mocked methods were simplified to avoid some complexity of the WithCancel.

**Comment by djmitche** [comment]
OK, if it's simpler this way, let's just do it this way :)

**Comment by morigs** [comment]
Ok, let me know if there will be need for WithCancel.
Looking forward for the next release!

**Comment by djmitche** [comment]
We'll see if an issue gets filed.  I'll make a new release soon (on the scale of days)!

**Comment by djmitche** [comment]
https://pkg.go.dev/github.com/benbjohnson/clock@v1.3.0

**Pull request merged**
